[BUG] giscus theme is different from FixIt theme when initialize
hugo-fixit/FixIt pull request #453
Opened 2024-06-22 10:40 UTC by Bendancom

在 `giscus` 初始化时因未修改其中 `<script>` 元素中的 `data-theme` 属性，导致其仍为默认的 `preferred_color_scheme`，会被自动推导至 `dark` 主题。
the attribute:data-theme in the `<script>` element isn't modified when the giscus initialize,which leads to the content of data-theme is also in default which is `preferred_color_scheme` and it automatically infer to dark theme.

2024-06-22 10:52 UTC, Bendancom reviewed
add a js script line to modify the data-theme when it is initialize

2024-06-22 12:18 UTC, Lruihao commented
感觉用 hugo template 直接处理比用 js 处理更好。

2024-06-22 12:43 UTC, Lruihao requested changes

2024-06-22 12:43 UTC, Lruihao commented on layouts/partials/single/comment.html
> +          document.querySelector("#giscus>script").setAttribute("data-theme",this.isDark ? "dark" : "light");
似乎这段内联 js 不会被执行，因为它会有限执行 src 的 js 文件。
还有 `this.isDark` 是没有定义的变量，尽管 theme.js 里有定义，但是要等到 theme.js 加载执行完的实例才能拿到， `this.fixit.isDark`。

最后就是，其实 theme.js 之前有做处理（_第一次收到消息时_）

https://github.com/hugo-fixit/FixIt/blob/b998371564b0a3911b457fd864a5cc82dbfbd5c3/assets/js/theme.js#L853-L868

2024-06-22 12:50 UTC, Bendancom commented on layouts/partials/single/comment.html
> +          document.querySelector("#giscus>script").setAttribute("data-theme",this.isDark ? "dark" : "light");
有看到过，但是我这不加载，在第一次加载时该消息发送失败。
然后 `hugo template` 是直接替换，但 `theme` 应该是一个状态，可以先开一篇 `light` 主题文章，切换为 `dark` 主题后退回主页再开一篇文章。
`this.isDark` 确实是没定义，但实际测下来问题确实是解决了的，也不知为何。
如下是问题的体现。
![屏幕截图 2024-06-22 174546](https://github.com/hugo-fixit/FixIt/assets/59361378/0e5e0f0d-355a-4ceb-9897-66408331d2c7)

2024-06-22 12:55 UTC, Lruihao commented on layouts/partials/single/comment.html
> +          document.querySelector("#giscus>script").setAttribute("data-theme",this.isDark ? "dark" : "light");
我再测试一下

2024-06-23 06:15 UTC, Lruihao commented
暂时无法复现，网络不太好的时候是无法切换的。

2024-06-23 06:15 UTC, closed without merging