⬆️ Chore(libs): update Waline from 2.15.8 to 3.4.1
hugo-fixit/FixIt pull request #556
Opened 2024-11-29 13:19 UTC by yureiita

`@waline/client@3.4.1/dist/waline.js` produced the following error:

![image](https://github.com/user-attachments/assets/b87c359b-94df-4dce-92be-c32909b1be0a)

The fix is to use `@waline/client@3.4.1/dist/waline.umd.js`

2024-11-29 15:13 UTC, Lruihao requested changes

2024-11-29 15:13 UTC, Lruihao commented on layouts/partials/single/comment.html
> +    {{- /* TODO adapted to Waline 3.4.1 */ -}}
I am wondering if waline 3.4.1 has added any new configurations that require FixIt to adapte?

2024-11-30 13:05 UTC, yureiita commented on layouts/partials/single/comment.html
> +    {{- /* TODO adapted to Waline 3.4.1 */ -}}
According to [Migration to @waline/client V3](https://waline.js.org/en/migration/v3.html), it's only removing support for older Node.js and browsers, some feature removal and CSS variable update.

Also looking at [Component Props](https://waline.js.org/en/reference/client/props.html), it seems there's no new configurations.

So I guess we can delete that line?

2024-11-30 13:07 UTC, Lruihao commented on layouts/partials/single/comment.html
> +    {{- /* TODO adapted to Waline 3.4.1 */ -}}
Yes, could you please delete this line? Thanks！

2024-11-30 13:41 UTC, Lruihao approved these changes

2024-11-30 13:43 UTC, merged